linters:
  disable-all: true
  enable:
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - exhaustive

linters-settings:
  staticcheck:
    go: '1.19'
  exhaustive:
    default-signifies-exhaustive: true